export const services = [
  {
    serviceId: 1,
    serviceName: 'Brazilian Massage',
    description: 'Jiu Jitsu 500',
    duration: '3 hrs',
    price: 2500,
    createdAt: 'Now',
    updatedAt: 'Now',
  },
  {
    serviceId: 2,
    serviceName: 'Pilipinas Massage',
    description: 'Karate 600',
    duration: '2 hrs',
    price: 1500,
    createdAt: 'Now',
    updatedAt: 'Now',
  },
  {
    serviceId: 3,
    serviceName: 'Spain Massage',
    description: 'MMA 100',
    duration: '1 hr',
    price: 4500,
    createdAt: 'Now',
    updatedAt: 'Now',
  },
  {
    serviceId: 4,
    serviceName: 'Speranza Massage',
    description: 'Arnis 600',
    duration: '4 hrs',
    price: 4500,
    createdAt: 'Now',
    updatedAt: 'Now',
  },
]
